version: '2'

services:

  PostgreSQL:
    restart: always
    image: sameersbn/postgresql:9.5
    hostname: postgresql
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=usr_redmine
      - DB_PASS=00PrPlRv8QguQD1VxE
      - DB_NAME=redmine
    volumes:
      - /srv/bd/postgresql:/var/lib/postgresql

  Redmine:
    image: sameersbn/redmine:3.3.7
    hostname: redmine
    container_name: redmine
    depends_on:
    - PostgreSQL
    environment:
    - America/Sao_Paulo

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=usr_redmine
    - DB_PASS=00PrPlRv8QguQD1VxE
    - DB_NAME=redmine

    - REDMINE_PORT=10083
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=false
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "8082:80"
    volumes:
    - /srv/apps/redmine/:/home/redmine/data
