version: '2'

services:
  JenkinsCI:
    restart: always
    image: liatrio/alpine-jenkins 
    hostname: jenkins
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/apps/jenkinsci:/var/jenkins_home
      - /srv:/srv
